/**
 * This class is generated by jOOQ
 */
package io.xys.skill.guessnumber.domain;


import javax.annotation.Generated;

import org.jooq.Record;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<Record> CONSTRAINT_B = UniqueKeys0.CONSTRAINT_B;
	public static final UniqueKey<Record> CONSTRAINT_B3 = UniqueKeys0.CONSTRAINT_B3;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<Record> CONSTRAINT_B = createUniqueKey(Numbers.NUMBERS, Numbers.NUMBERS.ID);
		public static final UniqueKey<Record> CONSTRAINT_B3 = createUniqueKey(Numbers.NUMBERS, Numbers.NUMBERS.USER_ID);
	}
}
