/**
 * This class is generated by jOOQ
 */
package io.xys.skill.guessnumber.domain;


import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.NUMBERS
	 */
	public static final Numbers NUMBERS = io.xys.skill.guessnumber.domain.Numbers.NUMBERS;
}
